### ISSUE TITLE
Add shape checking for deformable_groups?

### ISSUE THREAD

**Issue by GengDavid** [chengdazhi/Deformable-Convolution-V2-PyTorch#17]
I found that only deform_conv on the master branch has shape checking for ```deformable_groups```.  
 
It may cause incomprehensible Cuda Runtime Error when the number of the input channel is divisible by ```deformable_groups```.   

Maybe adding some shape checkings is more friendly to use and there's no need to compile again when adding it in Python codes.

Changes can be seen at [master branch](https://github.com/GengDavid/Deformable-Convolution-V2-PyTorch/commit/a1260705305a6d8e6a2cbbb3f60738a75ff9eaaf) and [pytorch_1.0.0 branch](https://github.com/GengDavid/Deformable-Convolution-V2-PyTorch/commit/248d1744b411bb8185b3042871fd02427511cb6e) in my repo.

**Comment by chengdazhi** [comment]
Thanks for your attention and modification. Feel free to send a pull request.
