### ISSUE TITLE
The number of filter for generate offset is [num_deformable_groups * 2 * kH * kW]?

### ISSUE THREAD

**Issue by gzhcv** [chengdazhi/Deformable-Convolution-V2-PyTorch#18]
Inside the paper of  Deformable ConvNets V2,  a modulation scalars was used to modulate the input feature amplitudes from different spatial locations/bins.  As the following description,

![image](https://user-images.githubusercontent.com/19361578/55274182-89eb6b80-5310-11e9-861f-746ae2035432.png)

So, i'm curious about the usage example of ` DeformConv() `  in ` test.py`  , which setting the number of filter for generate offset as `num_deformable_groups * 2 * kH * kW`.  Shouldn't it be `num_deformable_groups * 3 * kH * kW`? 

Thanks a lot for your code, hope for your reply.

**Comment by gzhcv** [comment]
One more question, i trained a Deformable ConvNets for Classification task and have gained accurancy. Then i extract the value feature map for predicting the offset,  which range from -99 to 99 approximately. This result also bothered me, whether the value should be squeezed to a  reasonable range, such as [-5, 5]

**Comment by xvjiarui** [comment]
`num_deformable_groups * 2 * kH * kW` is for **normal** Deformable Conv. 
`num_deformable_groups` * 3 * kH * kW` is for **modulated** Deformable Conv.

**Comment by gzhcv** [comment]
@xvjiarui Thanks for your reply!  The second question about the offset value range,  any help?
