### ISSUE TITLE
How to run build.py in windows10?   [cuda9、torch0.4.1、Python3.5]

### ISSUE THREAD

**Issue by zhuwanling** [chengdazhi/Deformable-Convolution-V2-PyTorch#24]
running: python build.py
get error:  cffi.VerificationError: CompileError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2

**Comment by zhuwanling** [comment]
python build.py
Including CUDA code.
F:\gooleDown\Deformable-Convolution-V2-PyTorch-master
generating C:\Users\fly\AppData\Local\Temp\tmpvm740wzd\_deform_conv.c
setting the current directory to 'C:\\Users\\fly\\AppData\\Local\\Temp\\tmpvm740wzd'
running build_ext
building '_deform_conv' extension
creating Release
creating Release\gooleDown
creating Release\gooleDown\Deformable-Convolution-V2-PyTorch-master
creating Release\gooleDown\Deformable-Convolution-V2-PyTorch-master\src
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DWITH_CUDA -ID:\code\annaconda\envs\python35_2\lib\site-packages\torch\utils\ffi\..\..\lib\include -ID:\code\annaconda\envs\python35_2\lib\site-packages\torch\utils\ffi\..\..\lib\include\TH -ID:\code\annaconda\envs\python35_2\lib\site-packages\torch\utils\ffi\..\..\lib\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2/include" "-IC:\Program Files\NVIDIA Corporation\NvToolsExt\/include" -ID:\code\annaconda\envs\python35_2\include -ID:\code\annaconda\envs\python35_2\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\winrt" /Tc_deform_conv.c /Fo.\Release\_deform_conv.obj -std=c99 -std=c++11
cl: 命令行 warning D9002 :忽略未知选项“-std=c99”
cl: 命令行 warning D9002 :忽略未知选项“-std=c++11”
_deform_conv.c
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DWITH_CUDA -ID:\code\annaconda\envs\python35_2\lib\site-packages\torch\utils\ffi\..\..\lib\include -ID:\code\annaconda\envs\python35_2\lib\site-packages\torch\utils\ffi\..\..\lib\include\TH -ID:\code\annaconda\envs\python35_2\lib\site-packages\torch\utils\ffi\..\..\lib\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2/include" "-IC:\Program Files\NVIDIA Corporation\NvToolsExt\/include" -ID:\code\annaconda\envs\python35_2\include -ID:\code\annaconda\envs\python35_2\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\winrt" /TcF:\gooleDown\Deformable-Convolution-V2-PyTorch-master\src\deform_conv.c /Fo.\Release\gooleDown\Deformable-Convolution-V2-PyTorch-master\src\deform_conv.obj -std=c99 -std=c++11
cl: 命令行 warning D9002 :忽略未知选项“-std=c99”
cl: 命令行 warning D9002 :忽略未知选项“-std=c++11”
deform_conv.c
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DWITH_CUDA -ID:\code\annaconda\envs\python35_2\lib\site-packages\torch\utils\ffi\..\..\lib\include -ID:\code\annaconda\envs\python35_2\lib\site-packages\torch\utils\ffi\..\..\lib\include\TH -ID:\code\annaconda\envs\python35_2\lib\site-packages\torch\utils\ffi\..\..\lib\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2/include" "-IC:\Program Files\NVIDIA Corporation\NvToolsExt\/include" -ID:\code\annaconda\envs\python35_2\include -ID:\code\annaconda\envs\python35_2\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\winrt" /TcF:\gooleDown\Deformable-Convolution-V2-PyTorch-master\src\deform_conv_cuda.c /Fo.\Release\gooleDown\Deformable-Convolution-V2-PyTorch-master\src\deform_conv_cuda.obj -std=c99 -std=c++11
cl: 命令行 warning D9002 :忽略未知选项“-std=c99”
cl: 命令行 warning D9002 :忽略未知选项“-std=c++11”
deform_conv_cuda.c
f:\gooledown\deformable-convolution-v2-pytorch-master\src\deform_conv_cuda_kernel.h(1): error C2143: 语法错误: 缺少“{”(在“<”的前面)
f:\gooledown\deformable-convolution-v2-pytorch-master\src\deform_conv_cuda_kernel.h(1): error C2059: 语法错误:“<”
f:\gooledown\deformable-convolution-v2-pytorch-master\src\deform_conv_cuda_kernel.h(10): error C2143: 语法错误: 缺少“{”(在“<”的前面)
f:\gooledown\deformable-convolution-v2-pytorch-master\src\deform_conv_cuda_kernel.h(10): error C2059: 语法错误:“<”
f:\gooledown\deformable-convolution-v2-pytorch-master\src\deform_conv_cuda_kernel.h(19): error C2143: 语法错误: 缺少“{”(在“<”的前面)
f:\gooledown\deformable-convolution-v2-pytorch-master\src\deform_conv_cuda_kernel.h(19): error C2059: 语法错误:“<”
F:\gooleDown\Deformable-Convolution-V2-PyTorch-master\src\deform_conv_cuda.c(65): warning C4244: “初始化”: 从“int64_t”转换到“long”，可能丢失数据
F:\gooleDown\Deformable-Convolution-V2-PyTorch-master\src\deform_conv_cuda.c(66): warning C4244: “初始化”: 从“int64_t”转换到“long”，可能丢失数据
F:\gooleDown\Deformable-Convolution-V2-PyTorch-master\src\deform_conv_cuda.c(67): warning C4244: “初始化”: 从“int64_t”转换到“long”，可能丢失数据
F:\gooleDown\Deformable-Convolution-V2-PyTorch-master\src\deform_conv_cuda.c(68): warning C4244: “初始化”: 从“int64_t”转换到“long”，可能丢失数据
F:\gooleDown\Deformable-Convolution-V2-PyTorch-master\src\deform_conv_cuda.c(206): warning C4013: “deformable_im2col”未定义；假设外部返回 int
F:\gooleDown\Deformable-Convolution-V2-PyTorch-master\src\deform_conv_cuda.c(150): warning C4244: “初始化”: 从“int64_t”转换到“long”，可能丢失数据
F:\gooleDown\Deformable-Convolution-V2-PyTorch-master\src\deform_conv_cuda.c(151): warning C4244: “初始化”: 从“int64_t”转换到“long”，可能丢失数据
F:\gooleDown\Deformable-Convolution-V2-PyTorch-master\src\deform_conv_cuda.c(152): warning C4244: “初始化”: 从“int64_t”转换到“long”，可能丢失数据
F:\gooleDown\Deformable-Convolution-V2-PyTorch-master\src\deform_conv_cuda.c(153): warning C4244: “初始化”: 从“int64_t”转换到“long”，可能丢失数据
F:\gooleDown\Deformable-Convolution-V2-PyTorch-master\src\deform_conv_cuda.c(155): warning C4244: “初始化”: 从“int64_t”转换到“long”，可能丢失数据
F:\gooleDown\Deformable-Convolution-V2-PyTorch-master\src\deform_conv_cuda.c(213): warning C4244: “初始化”: 从“int64_t”转换到“long”，可能丢失数据
F:\gooleDown\Deformable-Convolution-V2-PyTorch-master\src\deform_conv_cuda.c(340): warning C4013: “deformable_col2im_coord”未定义；假设外部返回 int
F:\gooleDown\Deformable-Convolution-V2-PyTorch-master\src\deform_conv_cuda.c(347): warning C4013: “deformable_col2im”未定义；假设外部返回 int
F:\gooleDown\Deformable-Convolution-V2-PyTorch-master\src\deform_conv_cuda.c(282): warning C4244: “初始化”: 从“int64_t”转换到“long”，可能丢失数据
F:\gooleDown\Deformable-Convolution-V2-PyTorch-master\src\deform_conv_cuda.c(283): warning C4244: “初始化”: 从“int64_t”转换到“long”，可能丢失数据
F:\gooleDown\Deformable-Convolution-V2-PyTorch-master\src\deform_conv_cuda.c(284): warning C4244: “初始化”: 从“int64_t”转换到“long”，可能丢失数据
F:\gooleDown\Deformable-Convolution-V2-PyTorch-master\src\deform_conv_cuda.c(285): warning C4244: “初始化”: 从“int64_t”转换到“long”，可能丢失数据
F:\gooleDown\Deformable-Convolution-V2-PyTorch-master\src\deform_conv_cuda.c(287): warning C4244: “初始化”: 从“int64_t”转换到“long”，可能丢失数据
F:\gooleDown\Deformable-Convolution-V2-PyTorch-master\src\deform_conv_cuda.c(331): warning C4244: “初始化”: 从“int64_t”转换到“long”，可能丢失数据
F:\gooleDown\Deformable-Convolution-V2-PyTorch-master\src\deform_conv_cuda.c(417): warning C4244: “初始化”: 从“int64_t”转换到“long”，可能丢失数据
F:\gooleDown\Deformable-Convolution-V2-PyTorch-master\src\deform_conv_cuda.c(418): warning C4244: “初始化”: 从“int64_t”转换到“long”，可能丢失数据
F:\gooleDown\Deformable-Convolution-V2-PyTorch-master\src\deform_conv_cuda.c(419): warning C4244: “初始化”: 从“int64_t”转换到“long”，可能丢失数据
F:\gooleDown\Deformable-Convolution-V2-PyTorch-master\src\deform_conv_cuda.c(420): warning C4244: “初始化”: 从“int64_t”转换到“long”，可能丢失数据
F:\gooleDown\Deformable-Convolution-V2-PyTorch-master\src\deform_conv_cuda.c(422): warning C4244: “初始化”: 从“int64_t”转换到“long”，可能丢失数据
F:\gooleDown\Deformable-Convolution-V2-PyTorch-master\src\deform_conv_cuda.c(465): warning C4244: “初始化”: 从“int64_t”转换到“long”，可能丢失数据
Traceback (most recent call last):
  File "D:\code\annaconda\envs\python35_2\lib\distutils\_msvccompiler.py", line 382, in compile
    self.spawn(args)
  File "D:\code\annaconda\envs\python35_2\lib\distutils\_msvccompiler.py", line 501, in spawn
    return super().spawn(cmd)
  File "D:\code\annaconda\envs\python35_2\lib\distutils\ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "D:\code\annaconda\envs\python35_2\lib\distutils\spawn.py", line 38, in spawn
    _spawn_nt(cmd, search_path, dry_run=dry_run)
  File "D:\code\annaconda\envs\python35_2\lib\distutils\spawn.py", line 81, in _spawn_nt
    "command %r failed with exit status %d" % (cmd, rc))
distutils.errors.DistutilsExecError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\code\annaconda\envs\python35_2\lib\site-packages\cffi\ffiplatform.py", line 51, in _build
    dist.run_command('build_ext')
  File "D:\code\annaconda\envs\python35_2\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "D:\code\annaconda\envs\python35_2\lib\site-packages\setuptools\command\build_ext.py", line 75, in run
    _build_ext.run(self)
  File "D:\code\annaconda\envs\python35_2\lib\distutils\command\build_ext.py", line 339, in run
    self.build_extensions()
  File "D:\code\annaconda\envs\python35_2\lib\distutils\command\build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "D:\code\annaconda\envs\python35_2\lib\distutils\command\build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "D:\code\annaconda\envs\python35_2\lib\site-packages\setuptools\command\build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "D:\code\annaconda\envs\python35_2\lib\distutils\command\build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "D:\code\annaconda\envs\python35_2\lib\distutils\_msvccompiler.py", line 384, in compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build.py", line 36, in <module>
    ffi.build()
  File "D:\code\annaconda\envs\python35_2\lib\site-packages\torch\utils\ffi\__init__.py", line 189, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "D:\code\annaconda\envs\python35_2\lib\site-packages\torch\utils\ffi\__init__.py", line 111, in _build_extension
    outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "D:\code\annaconda\envs\python35_2\lib\site-packages\cffi\api.py", line 723, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "D:\code\annaconda\envs\python35_2\lib\site-packages\cffi\recompiler.py", line 1526, in recompile
    compiler_verbose, debug)
  File "D:\code\annaconda\envs\python35_2\lib\site-packages\cffi\ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "D:\code\annaconda\envs\python35_2\lib\site-packages\cffi\ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.VerificationError: CompileError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2

**Comment by chengdazhi** [comment]
Hi, thank you for trying deformable conv. We never tried to support Windows, nor do we have any Windows environment to test our code. Please switch to Linux, it makes lives easier:)

**Comment by cqray1990** [comment]
@zhuwanling  i am also trying build dcn on windows？have you solved it?
thank you
