### ISSUE TITLE
How to get pretrain weight?

### ISSUE THREAD

**Issue by kaikaizhu** [chengdazhi/Deformable-Convolution-V2-PyTorch#39]
I want to increase dcn into backbone （resnet101）. Which weight should I use as the pre-training weight?

**Comment by kaikaizhu** [comment]
@chengdazhi Can you help me? Thanks!

**Comment by chengdazhi** [comment]
You can get pretrained models in mmdetection repo.
[https://github.com/open-mmlab/mmdetection/blob/master/configs/dcn/README.md](https://github.com/open-mmlab/mmdetection/blob/master/configs/dcn/README.md)

**Comment by kaikaizhu** [comment]
@chengdazhi  Thanks a lot!
Do you mean download the model as pretrain weights and use my own datasets to continue train?

**Comment by chengdazhi** [comment]
Yes, you can do that.
