### ISSUE TITLE
DCN on CPU 

### ISSUE THREAD

**Issue by abhigoku10** [chengdazhi/Deformable-Convolution-V2-PyTorch#46]
@chengdazhi  hi thanks for the wonderful code base , i had ffew queries just wanted to check if we can use DCN in the CPU also or does it particularly require the GPU

**Comment by AstaTus** [comment]
I have the same question

**Comment by chengdazhi** [comment]
Sorry for the late reply. We only provide GPU version. Shouldn't be hard to change it to CPU only, though.

**Comment by meirashaf** [comment]
> Sorry for the late reply. We only provide GPU version. Shouldn't be hard to change it to CPU only, though.

do you have any instruction/tutorial on how to do it?
