### ISSUE TITLE
Download model from Google Driven Drive is unavailable

### ISSUE THREAD

**Issue by LeonYF** [chengdazhi/Deformable-Convolution-V2-PyTorch#55]
Hi! I tried to download the model of Deformable ConvNet v2 from Google Drive, but the link is no longer available. And the downloaded models from Baidu NetDisk can not be unzipped with unknown reasons. Could you please to check what is wrong with the model link with Google Drive? Many thanks.

**Comment by chengdazhi** [comment]
Please use the models in mmdetection repo.
