### ISSUE TITLE
import error in Pytorch1.0.0 Implementation

### ISSUE THREAD

**Issue by WERush** [chengdazhi/Deformable-Convolution-V2-PyTorch#7]
Hi,
I finish the installation by using branch 'pytorch1.0.0';
When I run the test.py, an "import error" occurs as following:
```python
ModuleNotFoundError: No module named 'dcn'
```

Then I replace the 'dcn' with 'DCN', another error occurs:
```python
import Error: site-packages/DCN-1.0-py3.7-linux-x86_64.egg/DCN.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN2at19UndefinedTensorImpl10_singletonE
```

**Comment by xvjiarui** [comment]
Hi, sorry for the trouble. It is a historical issue. 
I already updated import path and test.py.

**Comment by WERush** [comment]
Hi, 
Thanks for your reply.
I update and reinstall the pytorch1.0 version. Now, I encounter the segmentation fault when I run the following code.

```python

def example_dconv():
    input = torch.randn(2, 64, 128, 128).cuda()
    # wrap all things (offset and mask) in DCN
    dcn = DeformConvPack(64, 128, kernel_size=(3, 3), stride=1,
              padding=1, groups=2, deformable_groups=2).cuda()
    # print(dcn.weight.shape, input.shape)
    output = dcn(input) # The segmentation fault occurs at here!

```

**Comment by WERush** [comment]
I have tried (cuda9.0 and cudnn7.3) and (cuda8.0 and cudnn5), and all of them pass the installation while encourage the same segmentation fault. That's so weird. Any hints?

**Comment by TSSSS4** [comment]
> Sorry, I couldn't reproduce this error. I am using cuda 9.0 and cudnn 7.
> May I know your environment? Btw, do you have the same error in pytorch 0.4.1 version?

I've got the same problem with SIGSEGV while running test.py, and pytorch 0.4.1 version works well

**Comment by xvjiarui** [comment]
@TSSSS4 Thanks for your information. 
Anyone who encountered segmentation fault please try to change your gcc >=4.9. 
Btw, sorry for the late reply. Feel free to reopen this issue if this doesn't help.

**Comment by cjnjuwhy** [comment]
I have the same problem `python-37m-x86_64-linux-gnu.so: undefined symbol: _ZN2at19UndefinedTensorImpl10_singletonE` when import DCN in python files or ipython.
But the error doesn't appear when I use Jupyter Notebook ....
