### ISSUE TITLE
what is the meaning of num_deformable_groups， and how to use this parameter? 

### ISSUE THREAD

**Issue by miracle-fmh** [chengdazhi/Deformable-Convolution-V2-PyTorch#8]
Does the code support group convolution? what is the meaning of num_deformable_groups， and how to use this parameter?   Is the role of "num_deformable_groups" same as the "groups" in nn.Conv2d function? 3Q

**Comment by chengdazhi** [comment]
Our code doesn't support group conv by now. The parameter num_deformable_groups means how many group of offsets an DeformConv operator takes. 

For example, if num_deformable_groups=4, then four sets of deformable offsets must be given. The input channels are divided into 4 groups, and one set of offset operators on one group of input channels.

Normally, num_deformable_groups=1 is good enough. Increasing it will bring marginal gains.

**Comment by miracle-fmh** [comment]
@chengdazhi   I am wonder that the detection performance (by using deformable  convolution  in the  group conv, such as ResNeXt-Deformabel ) can be improved or not. Have you  done such experiments?

**Comment by chengdazhi** [comment]
Haven't done that before.
